version: '3.9'

services:
  web:
    build: .
    container_name: reflections-be
    restart: always
    command: gunicorn reflectionsBE.wsgi:application --bind 0.0.0.0:8000 --workers 4
    ports:
      - "8000:8000"   # Django server accessible on localhost:8000
    env_file:
      - .env
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"